version: '3.9'

services:
  wiremock:
    build:
      context: ./
      dockerfile: Dockerfile
    image: wiremock-custom
    container_name: wiremock-credit-restriction-api
    ports:
      - "8088:80"
    volumes:
      # we copy our scripts onto the container
      - ./__files:/wiremock-jre8-standalone/__files
      - ./mappings:/wiremock-jre8-standalone/mappings
